/**
 * CONFIGURACIÓN CENTRAL SIGC.
 * Cambie únicamente SPREADSHEET_ID al instalar el sistema en otra planilla.
 */
const SIGC_CONFIG = Object.freeze({
  VERSION: '3.6.14',
  SPREADSHEET_ID: '1gT0135EeC1MTzLSfcfJOHuJl5yODFyDtL7eXRfTRmuo',
  ZONA_HORARIA: 'America/Santiago',
  LIMITE_RECUPERACION_FORMULARIO: 100,
  CACHE_RESUMEN_SEGUNDOS: 21600,
  CACHE_FORMULARIOS_SEGUNDOS: 300,
  LIMITE_ACTIVADORES_PROYECTO: 20,
  MAX_FORMULARIOS_RECOMENDADO: 15,
  HOJAS: Object.freeze({
    PERSONAS: 'PERSONAS',
    INTERESES: 'INTERESES_CAPACITACION',
    PERFILES_BASE_MADRE: 'PERFILES_BASE_MADRE',
    FORMULARIOS: 'CONFIG_FORMULARIOS',
    ACTIVIDADES: 'ACTIVIDADES',
    PARTICIPACIONES: 'PARTICIPACIONES',
    ASISTENCIA: 'ASISTENCIA_RAPIDA',
    BUSCADOR: 'BUSCADOR_PERSONA',
    CALIDAD: 'CONTROL_CALIDAD',
    RESPUESTAS: 'RESPUESTAS_FORMULARIO',
    IMPORTAR: 'IMPORTAR_ASISTENTES',
    HISTORIAL_IMPORTACIONES: 'HISTORIAL_IMPORTACIONES',
    HISTORICO_ORIGINAL: 'HISTORICO_ORIGINAL',
    LOG: 'LOG_CAMBIOS',
    AUDITORIA: 'AUDITORIA_MIGRACION'
  })
});
/* Alias de compatibilidad con el código histórico. */
const SISTEMA = Object.freeze({
  HOJAS: SIGC_CONFIG.HOJAS,
  ZONA_HORARIA: SIGC_CONFIG.ZONA_HORARIA
});
const WEBAPP_CONFIG = Object.freeze({
  SPREADSHEET_ID: SIGC_CONFIG.SPREADSHEET_ID,
  ZONA_HORARIA: SIGC_CONFIG.ZONA_HORARIA,
  HOJAS: SIGC_CONFIG.HOJAS
});
